### ISSUE TITLE
?!

### ISSUE THREAD

**Issue by joppekoers** [MyNameIsTrez/webserv#20]
What in the name of all that is holy is this?
https://github.com/MyNameIsTrez/webserv/blob/d441743b8d6dffa6ec4568dfff04d1668ed9521a/src/Client.cpp#L36-L51)

**Comment by MyNameIsTrez** [comment]
![image](https://github.com/MyNameIsTrez/webserv/assets/32989873/269179bd-f7b4-4fa5-a1ae-db94f479a160)

https://blog.tartanllama.xyz/initialization-is-bonkers/
